# Site settings
title: Developer MeetUp Freiburg
contact: Sebastian Sebald
email: devsmeetup@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Developer MeetUp ist ein Software Engineering und Developer MeetUp in
  Freiburg.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://devsmeetup.de" # the base hostname & protocol for your site
twitter_username: devsmeetup
github_username:  devsmeetup

# Build settings
markdown: kramdown

future: true

exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - bower_components
  - bower.json
